'use strict';
const cases=[{id:'checkout',title:'checkout race',repo:'payments-api',framework:'pytest',meta:'最近一次失败 12 分钟前',command:'pytest tests/test_checkout.py::test_parallel_capture -q',runs:18,fail:7},{id:'cache',title:'cache invalidation',repo:'catalog-service',framework:'Jest',meta:'最近一次失败 2 小时前',command:'npm test -- cache/invalidation.spec.ts',runs:42,fail:9},{id:'timezone',title:'timezone boundary',repo:'billing-worker',framework:'Go test',meta:'最近一次失败 昨天',command:'go test ./internal/billing -run TestMonthEnd',runs:31,fail:4}];
let activeCase=0, view='lab', matrixShown=6, running=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const runData=[
 ['#018','auth → capture → refund','42','4','UTC','失败','2.84s'],['#017','auth → refund → capture','42','4','UTC','通过','2.61s'],['#016','capture → auth → refund','17','4','UTC','失败','2.79s'],['#015','auth → capture → refund','08','1','UTC','通过','1.42s'],['#014','refund → capture → auth','42','8','UTC','失败','3.05s'],['#013','auth → capture → refund','31','4','UTC','通过','2.68s'],['#012','capture → refund → auth','42','4','UTC','失败','2.81s'],['#011','auth → capture → refund','09','1','UTC','通过','1.39s'],['#010','auth → refund → capture','42','8','UTC','失败','3.11s'],['#009','capture → auth → refund','77','4','UTC','通过','2.73s'],['#008','auth → capture → refund','42','4','UTC','失败','2.88s'],['#007','refund → auth → capture','13','4','UTC','通过','2.55s']];
const suspects=[['并发度 = 4+','0.91','并发 worker 共享 capture fixture'],['seed = 42','0.78','7/9 失败样本使用固定 seed'],['顺序：capture → refund','0.64','失败集中在相邻状态转换'],['缓存状态','0.31','冷启动时未复现']];
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function renderCases(){ $('#caseCount').textContent=cases.length;$('#caseList').innerHTML=cases.map((c,i)=>`<button class="case-item ${i===activeCase?'active':''}" data-case="${i}"><i class="case-dot"></i><div><b>${c.title}</b><small>${c.repo} · ${c.framework}</small></div></button>`).join('') }
function current(){return cases[activeCase]}
function renderMatrix(){const rows=runData.slice(0,matrixShown);$('#matrixBody').innerHTML=rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td><span class="result ${r[5]==='失败'?'fail':'pass'}">${r[5]}</span></td><td>${r[6]}</td></tr>`).join('');$('#loadMoreBtn').textContent=matrixShown>=runData.length?'已展示全部运行':'加载全部 ${current().runs} 次运行 →'}
function renderSuspects(){$('#suspects').innerHTML=suspects.map(s=>`<div class="suspect"><div class="suspect-head"><b>${s[0]}</b><span>${s[1]}</span></div><div class="bar"><i style="width:${Number(s[1])*100}%"></i></div><small style="display:block;color:#98a4b3;font-size:10px;margin-top:5px">${s[2]}</small></div>`).join('')}
function renderRuns(){$('#runList').innerHTML='<div class="run-row header"><span>RUN</span><span>配置</span><span>结果</span><span>耗时</span><span>时间</span></div>'+runData.concat(runData.slice(0,6)).map((r,i)=>`<div class="run-row"><span>${r[0]}</span><span>${r[1]} · c=${r[3]}</span><span class="${r[5]==='失败'?'fail':'pass'}">${r[5]}</span><span>${r[6]}</span><span>${i<3?'刚刚':(i+1)+' 分钟前'}</span></div>`).join('')}
function reportMarkdown(){const c=current();return `# ${c.title} / 复现报告\n\n## 结论\n在 ${c.runs} 次运行中复现 ${c.fail} 次（${(c.fail/c.runs*100).toFixed(1)}%）。最可能原因是并发 worker 共享 fixture，seed=42 与特定执行顺序会放大问题。\n\n## 嫌疑变量\n1. 并发度 = 4+（相关性 0.91）\n2. seed = 42（相关性 0.78）\n3. capture → refund 顺序（相关性 0.64）\n\n## 最小复现\n\`pytest tests/test_checkout.py::test_parallel_capture -q -n 4 --randomly-seed=42\`\n\n## 下一步\n固定 seed=42，关闭顺序扰动，依次扫描并发度 1/2/4；检查 capture fixture 的生命周期与共享状态。\n`}
function renderReport(){$('#reportTitle').textContent=current().title+' / 复现报告';$('#reportBody').innerHTML='<h3>结论</h3><p>在 <b>'+current().runs+' 次</b>运行中复现 <b>'+current().fail+' 次</b>（'+(current().fail/current().runs*100).toFixed(1)+'%）。最可能原因是并发 worker 共享 fixture，seed=42 与特定执行顺序会放大问题。</p><h3>嫌疑变量</h3><ol><li>并发度 = 4+（相关性 0.91）</li><li>seed = 42（相关性 0.78）</li><li>capture → refund 顺序（相关性 0.64）</li></ol><h3>最小复现命令</h3><pre>pytest tests/test_checkout.py::test_parallel_capture -q -n 4 --randomly-seed=42</pre><h3>下一步</h3><p>固定 seed=42，关闭顺序扰动，依次扫描并发度 1/2/4；检查 capture fixture 的生命周期与共享状态。</p>'}
function render(){const c=current();$('#crumbTitle').textContent=c.title;$('#caseTitle').textContent=c.title;$('#caseMeta').textContent=c.repo+' · '+c.framework+' · '+c.meta;$('#commandText').textContent=c.command;$('#totalRuns').textContent=c.runs;$('#runCount').textContent=c.runs;$('#failRuns').textContent=c.fail;$('#reproRate').textContent=(c.fail/c.runs*100).toFixed(1)+'%';renderCases();renderMatrix();renderSuspects();renderRuns();renderReport()}
function setView(v){view=v;$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#labView').classList.toggle('hidden',v!=='lab');$('#runsView').classList.toggle('hidden',v!=='runs');$('#reportsView').classList.toggle('hidden',v!=='reports')}
function startRun(){if(running)return;running=true;const n=Math.max(2,Math.min(100,Number($('#repeatInput').value)||24));$('#runProgress').classList.remove('hidden');$('#startRunBtn').disabled=true;let i=0;const timer=setInterval(()=>{i++;$('#progressText').textContent=i+' / '+n;$('#progressBar').style.width=(i/n*100)+'%';if(i>=n){clearInterval(timer);running=false;$('#startRunBtn').disabled=false;$('#runProgress').classList.add('hidden');const fail=Math.max(1,Math.round(n*.35+Math.random()*n*.12));current().runs+=n;current().fail+=fail;matrixShown=6;render();toast('实验完成：'+fail+' 次失败，已更新嫌疑变量')}} ,70)}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function bind(){document.body.addEventListener('click',e=>{const c=e.target.closest('[data-case]');if(c){activeCase=Number(c.dataset.case);matrixShown=6;render();return}const v=e.target.closest('[data-view]');if(v)setView(v.dataset.view)});$('#runBtn').onclick=()=>{setView('lab');startRun()};$('#startRunBtn').onclick=startRun;$('#loadMoreBtn').onclick=()=>{matrixShown=runData.length;renderMatrix()};$('#snapshotBtn').onclick=()=>toast('环境快照已保存到本地');$('#saveNoteBtn').onclick=()=>{localStorage.ftiNote=$('#notes').value;toast('调查笔记已保存')};$('#copyReportBtn').onclick=()=>navigator.clipboard?.writeText(reportMarkdown()).then(()=>toast('报告已复制'));$('#downloadReportBtn').onclick=()=>download(current().title+'-report.md',reportMarkdown());$('#exportRunsBtn').onclick=()=>download(current().title+'-runs.json',JSON.stringify({case:current(),runs:runData},null,2),'application/json');$('#newCaseBtn').onclick=$('#addCaseBtn').onclick=()=>{const title=prompt('调查名称','new flaky case');if(title){cases.push({id:Date.now(),title,repo:'new-repository',framework:'pytest',meta:'刚刚创建',command:'pytest tests/test_target.py -q',runs:0,fail:0});activeCase=cases.length-1;render();toast('已创建调查')}};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const f=e.target.files[0];if(f){toast('已导入 '+f.name+'，可在实验室中继续配置')}};$('#editCommand').onclick=()=>{const n=prompt('编辑测试命令',$('#commandText').textContent);if(n){current().command=n;render()}};$('#pasteLogBtn').onclick=()=>toast('请将日志文件拖入导入案例，或粘贴到调查笔记');$('#expandEnvBtn').onclick=()=>toast('环境快照包含依赖锁、系统变量与 git SHA')};render();bind();if(localStorage.ftiNote)$('#notes').value=localStorage.ftiNote;

